language: c++
dist: trusty
compiler:
    - clang
    - gcc
os:
    - linux
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install libboost1.55-dev libboost-system1.55-dev libboost-filesystem1.55-dev
before_script:
    - mkdir -p build
    - cd build
script:
    - cmake ..
    - make
    - make run_tests
