language: c++
dist: trusty
compiler:
    - clang++
os:
    - linux
before_install:
    - sudo apt-get update
install:
    - sudo apt list --installed | fgrep boost
    - sudo apt-get install clang++-3.9
    - sudo ln -s /usr/bin/clang-3.9 /usr/bin/clang
    - sudo ln -s /usr/bin/clang++-3.9 /usr/bin/clang++
    - wget http://dl.bintray.com/boostorg/release/1.65.0/source/boost_1_65_0.tar.gz
    - tar xzf boost_1_65_0.tar.gz
    - cd boost_1_65_0
    - ./bootstrap.sh --prefix=/usr/local --with-libraries=system,thread,date_time,regex,serialization,filesystem
    - ./b2 clean
    - ./b2 toolset=clang cxxflags="-std=c++11 -stdlib=libc++" linkflags="-stdlib=libc++" --prefix=/usr/local -j 4
    - sudo ./b2 install toolset=clang cxxflags="-std=c++11 -stdlib=libc++" linkflags="-stdlib=libc++" prefix=/usr/local >/dev/null
    - cd ..
before_script:
    - mkdir -p build
    - cd build
script:
    - cmake ..
    - make
    - make run_tests
